[package]
name = "resolver"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
dns-parser = "0.8.0"
dotenv = "0.15.0"
rand = "0.9.0"
toml = "0.8.19"
